"""Fachada de serviço do domínio Compras para a camada de apresentação.

Nesta etapa a implementação delega ao domínio empresarial existente. O ponto
de entrada estável permite decompor persistência e regras internas nas próximas
versões sem obrigar as telas a conhecer a estrutura concreta do backend.
"""

from enterprise.compras import (
    ACOES_COMPRAS,
    adicionar_aditivo,
    adicionar_comentario,
    adicionar_contato_fornecedor,
    agendar_relatorio,
    analisar_compras,
    aprovar_pedido,
    atualizar_status_pedido,
    avaliar_fornecedor,
    atualizar_fornecedor,
    criar_categoria,
    criar_contrato,
    criar_cotacao,
    criar_fornecedor,
    criar_item_catalogo,
    criar_pedido,
    criar_solicitacao,
    decidir_solicitacao,
    enviar_pedido,
    enviar_solicitacao,
    gerar_alertas_compras,
    gerar_pdf_pedido,
    gerar_relatorio_compras,
    garantir_catalogos,
    homologar_fornecedor,
    integrar_recebimento_financeiro,
    listar_historico,
    listar_secao,
    obter_fornecedores_cotacao,
    obter_itens_pedido,
    obter_itens_solicitacao,
    registrar_negociacao,
    registrar_documento_fornecedor,
    registrar_divergencia_manual,
    registrar_proposta,
    registrar_recebimento,
    resolver_alerta,
    resolver_divergencia,
    resumo_compras,
    selecionar_fornecedor,
    salvar_regra_aprovacao,
    tem_permissao_compras,
)

__all__ = (
    "ACOES_COMPRAS",
    "adicionar_aditivo",
    "adicionar_comentario",
    "adicionar_contato_fornecedor",
    "agendar_relatorio",
    "analisar_compras",
    "aprovar_pedido",
    "atualizar_status_pedido",
    "avaliar_fornecedor",
    "atualizar_fornecedor",
    "criar_categoria",
    "criar_contrato",
    "criar_cotacao",
    "criar_fornecedor",
    "criar_item_catalogo",
    "criar_pedido",
    "criar_solicitacao",
    "decidir_solicitacao",
    "enviar_pedido",
    "enviar_solicitacao",
    "gerar_alertas_compras",
    "gerar_pdf_pedido",
    "gerar_relatorio_compras",
    "garantir_catalogos",
    "homologar_fornecedor",
    "integrar_recebimento_financeiro",
    "listar_historico",
    "listar_secao",
    "obter_fornecedores_cotacao",
    "obter_itens_pedido",
    "obter_itens_solicitacao",
    "registrar_negociacao",
    "registrar_documento_fornecedor",
    "registrar_divergencia_manual",
    "registrar_proposta",
    "registrar_recebimento",
    "resolver_alerta",
    "resolver_divergencia",
    "resumo_compras",
    "selecionar_fornecedor",
    "salvar_regra_aprovacao",
    "tem_permissao_compras",
)
