"""Fachada de serviço do domínio Estoque para a camada de apresentação.

Nesta etapa a implementação delega ao domínio empresarial existente. O ponto
de entrada estável permite decompor persistência e regras internas nas próximas
versões sem obrigar as telas a conhecer a estrutura concreta do backend.
"""

from enterprise.estoque import (
    ACOES_ESTOQUE,
    agendar_relatorio,
    analisar_estoque,
    aprovar_inventario,
    aprovar_operacao,
    atualizar_item,
    calcular_reposicao,
    cancelar_operacao,
    conferir_operacao,
    confirmar_operacao,
    criar_categoria,
    criar_deposito,
    criar_fornecedor,
    criar_item,
    criar_localizacao,
    criar_operacao,
    criar_reserva,
    criar_solicitacao,
    decidir_solicitacao,
    encaminhar_reposicao_compras,
    finalizar_inventario,
    gerar_alertas_estoque,
    gerar_relatorio_estoque,
    iniciar_inventario,
    itens_inventario,
    liberar_reserva,
    listar_auditoria_estoque,
    listar_catalogos,
    listar_inventarios,
    listar_itens,
    listar_movimentacoes,
    listar_operacoes,
    listar_reservas,
    listar_secao,
    obter_item,
    obter_primeiro_item_operacao,
    receber_transferencia,
    registrar_contagem,
    registrar_ocorrencia,
    resolver_alerta,
    resumo_estoque,
    tem_permissao_estoque,
)

__all__ = (
    "ACOES_ESTOQUE",
    "agendar_relatorio",
    "analisar_estoque",
    "aprovar_inventario",
    "aprovar_operacao",
    "atualizar_item",
    "calcular_reposicao",
    "cancelar_operacao",
    "conferir_operacao",
    "confirmar_operacao",
    "criar_categoria",
    "criar_deposito",
    "criar_fornecedor",
    "criar_item",
    "criar_localizacao",
    "criar_operacao",
    "criar_reserva",
    "criar_solicitacao",
    "decidir_solicitacao",
    "encaminhar_reposicao_compras",
    "finalizar_inventario",
    "gerar_alertas_estoque",
    "gerar_relatorio_estoque",
    "iniciar_inventario",
    "itens_inventario",
    "liberar_reserva",
    "listar_auditoria_estoque",
    "listar_catalogos",
    "listar_inventarios",
    "listar_itens",
    "listar_movimentacoes",
    "listar_operacoes",
    "listar_reservas",
    "listar_secao",
    "obter_item",
    "obter_primeiro_item_operacao",
    "receber_transferencia",
    "registrar_contagem",
    "registrar_ocorrencia",
    "resolver_alerta",
    "resumo_estoque",
    "tem_permissao_estoque",
)
