"""Fachada de serviço do domínio Financeiro para a camada de apresentação.

Nesta etapa a implementação delega ao domínio empresarial existente. O ponto
de entrada estável permite decompor persistência e regras internas nas próximas
versões sem obrigar as telas a conhecer a estrutura concreta do backend.
"""

from enterprise.financeiro import (
    NATUREZAS,
    STATUS_ABERTOS,
    STATUS_TERMINAIS,
    analisar_financeiro,
    agendar_relatorio,
    anexar_documento,
    atualizar_lancamento,
    atualizar_status_vencidos,
    calcular_dre,
    cancelar_lancamento,
    conciliar_item,
    contabilizar_lancamento,
    criar_categoria,
    criar_conta,
    criar_lancamento,
    criar_parte,
    decidir_aprovacao,
    estornar_lancamento,
    gerar_alertas_financeiros,
    gerar_recorrencias_pendentes,
    gerar_relatorio_financeiro,
    importar_extrato,
    listar_aprovacoes_financeiras,
    listar_auditoria_financeira,
    listar_cartoes,
    listar_catalogos,
    listar_conciliacoes,
    listar_contas_com_saldo,
    listar_lancamentos,
    listar_orcamentos,
    listar_recorrencias,
    listar_relatorios_agendados,
    obter_lancamento,
    projetar_fluxo_caixa,
    registrar_baixa,
    resumo_financeiro,
    salvar_cartao,
    salvar_orcamento,
    salvar_plano_conta,
    submeter_aprovacao,
    tem_permissao_financeira,
)

__all__ = (
    "NATUREZAS",
    "STATUS_ABERTOS",
    "STATUS_TERMINAIS",
    "analisar_financeiro",
    "agendar_relatorio",
    "anexar_documento",
    "atualizar_lancamento",
    "atualizar_status_vencidos",
    "calcular_dre",
    "cancelar_lancamento",
    "conciliar_item",
    "contabilizar_lancamento",
    "criar_categoria",
    "criar_conta",
    "criar_lancamento",
    "criar_parte",
    "decidir_aprovacao",
    "estornar_lancamento",
    "gerar_alertas_financeiros",
    "gerar_recorrencias_pendentes",
    "gerar_relatorio_financeiro",
    "importar_extrato",
    "listar_aprovacoes_financeiras",
    "listar_auditoria_financeira",
    "listar_cartoes",
    "listar_catalogos",
    "listar_conciliacoes",
    "listar_contas_com_saldo",
    "listar_lancamentos",
    "listar_orcamentos",
    "listar_recorrencias",
    "listar_relatorios_agendados",
    "obter_lancamento",
    "projetar_fluxo_caixa",
    "registrar_baixa",
    "resumo_financeiro",
    "salvar_cartao",
    "salvar_orcamento",
    "salvar_plano_conta",
    "submeter_aprovacao",
    "tem_permissao_financeira",
)
