"""Fachada estável do Marketing especializado V10.3.0."""
from enterprise.marketing import (
    STATUS_CAMPANHA,
    analisar_marketing,
    atualizar_status_campanha,
    criar_automacao,
    criar_campanha,
    criar_canal,
    criar_conteudo,
    exportar_dataframe_marketing,
    listar_automacoes,
    contar_campanhas,
    listar_campanhas,
    listar_canais,
    listar_conteudos,
    registrar_metricas,
    resumo_marketing,
)
from enterprise.crm import (
    atualizar_lead_status,
    criar_contato,
    criar_empresa_crm,
    criar_lead,
    listar_contatos,
    listar_empresas_crm,
    listar_leads,
    registrar_atividade,
    resumo_crm,
)

__all__ = (
    "STATUS_CAMPANHA",
    "analisar_marketing",
    "atualizar_status_campanha",
    "criar_automacao",
    "criar_campanha",
    "criar_canal",
    "criar_conteudo",
    "exportar_dataframe_marketing",
    "listar_automacoes",
    "contar_campanhas",
    "listar_campanhas",
    "listar_canais",
    "listar_conteudos",
    "registrar_metricas",
    "resumo_marketing",
    "atualizar_lead_status",
    "criar_contato",
    "criar_empresa_crm",
    "criar_lead",
    "listar_contatos",
    "listar_empresas_crm",
    "listar_leads",
    "registrar_atividade",
    "resumo_crm",
)
