"""Fachada de serviço do domínio Rh para a camada de apresentação.

Nesta etapa a implementação delega ao domínio empresarial existente. O ponto
de entrada estável permite decompor persistência e regras internas nas próximas
versões sem obrigar as telas a conhecer a estrutura concreta do backend.
"""

from enterprise.rh import (
    ACOES_RH,
    adicionar_candidato,
    adicionar_dependente,
    adicionar_evento_folha,
    agendar_relatorio,
    analisar_rh,
    abrir_folha,
    alterar_estado_registro_rh,
    atualizar_admissao,
    atualizar_colaborador,
    concluir_desligamento,
    criar_solicitacao,
    criar_colaborador,
    criar_vaga,
    decidir_ferias_ausencia,
    decidir_solicitacao,
    exportar_dataframe_rh,
    fechar_folha,
    gerar_contracheque,
    gerar_relatorio_rh,
    iniciar_admissao,
    iniciar_desligamento,
    inscrever_treinamento,
    listar_admissoes,
    listar_auditoria_rh,
    listar_catalogos,
    listar_colaboradores,
    listar_secao,
    obter_colaborador,
    registrar_documento,
    registrar_ponto,
    resumo_rh,
    salvar_avaliacao,
    salvar_beneficio,
    salvar_cargo,
    salvar_pdi,
    salvar_permissao_acao,
    salvar_treinamento,
    solicitar_ferias_ausencia,
    tem_permissao_rh,
    verificar_documento,
    vincular_equipamento,
    vincular_beneficio,
)

__all__ = (
    "ACOES_RH",
    "adicionar_candidato",
    "adicionar_dependente",
    "adicionar_evento_folha",
    "agendar_relatorio",
    "analisar_rh",
    "abrir_folha",
    "alterar_estado_registro_rh",
    "atualizar_admissao",
    "atualizar_colaborador",
    "concluir_desligamento",
    "criar_solicitacao",
    "criar_colaborador",
    "criar_vaga",
    "decidir_ferias_ausencia",
    "decidir_solicitacao",
    "exportar_dataframe_rh",
    "fechar_folha",
    "gerar_contracheque",
    "gerar_relatorio_rh",
    "iniciar_admissao",
    "iniciar_desligamento",
    "inscrever_treinamento",
    "listar_admissoes",
    "listar_auditoria_rh",
    "listar_catalogos",
    "listar_colaboradores",
    "listar_secao",
    "obter_colaborador",
    "registrar_documento",
    "registrar_ponto",
    "resumo_rh",
    "salvar_avaliacao",
    "salvar_beneficio",
    "salvar_cargo",
    "salvar_pdi",
    "salvar_permissao_acao",
    "salvar_treinamento",
    "solicitar_ferias_ausencia",
    "tem_permissao_rh",
    "verificar_documento",
    "vincular_equipamento",
    "vincular_beneficio",
)
