"""Catálogo único de módulos, formulários e apresentação da V5.1."""

from __future__ import annotations


MODULOS = {
    "analytics": {
        "nome": "Analytics",
        "icone": "◈",
        "descricao": "Motor analítico, qualidade, dashboards e relatórios.",
        "cor": "#38BDF8",
        "entidade": None,
    },
    "rh": {
        "nome": "Recursos Humanos",
        "icone": "♙",
        "descricao": "Colaboradores, admissões, desligamentos e custos de pessoas.",
        "cor": "#A78BFA",
        "entidade": "colaboradores",
        "titulo_registro": "Novo colaborador",
        "colunas_tabela": (
            ("nome", "Colaborador", 190),
            ("cargo", "Cargo", 150),
            ("departamento_nome", "Departamento", 140),
            ("salario", "Salário", 100),
            ("status", "Situação", 95),
        ),
        "campos": (
            ("nome", "Nome completo", "texto", True),
            ("email", "E-mail corporativo", "texto", False),
            ("cargo", "Cargo", "texto", True),
            ("departamento_id", "Departamento", "departamento", False),
            ("centro_custo_id", "Centro de custo", "centro_custo", False),
            ("salario", "Salário", "decimal", False),
            ("admissao", "Data de admissão", "data", False),
            ("status", "Situação", ("Ativo", "Afastado", "Desligado"), True),
        ),
    },
    "financeiro": {
        "nome": "Financeiro",
        "icone": "₿",
        "descricao": "Receitas, despesas, vencimentos e fluxo de caixa.",
        "cor": "#22C55E",
        "entidade": "lancamentos_financeiros",
        "titulo_registro": "Novo lançamento",
        "colunas_tabela": (
            ("descricao", "Descrição", 210),
            ("tipo", "Tipo", 85),
            ("categoria", "Categoria", 130),
            ("valor", "Valor", 110),
            ("vencimento", "Vencimento", 105),
            ("status", "Status", 95),
        ),
        "campos": (
            ("descricao", "Descrição", "texto", True),
            ("tipo", "Tipo", ("Receita", "Despesa"), True),
            ("categoria", "Categoria", "texto", False),
            ("centro_custo_id", "Centro de custo", "centro_custo", False),
            ("valor", "Valor", "decimal", True),
            ("vencimento", "Vencimento", "data", False),
            ("status", "Status", ("Pendente", "Pago", "Recebido", "Cancelado"), True),
        ),
    },
    "estoque": {
        "nome": "Estoque",
        "icone": "▣",
        "descricao": "Itens, níveis mínimos, custos e movimentações.",
        "cor": "#F59E0B",
        "entidade": "itens_estoque",
        "titulo_registro": "Novo item",
        "colunas_tabela": (
            ("codigo", "Código", 100),
            ("descricao", "Descrição", 210),
            ("categoria", "Categoria", 120),
            ("quantidade", "Atual", 75),
            ("estoque_minimo", "Mínimo", 75),
            ("localizacao", "Localização", 120),
        ),
        "campos": (
            ("codigo", "Código / SKU", "texto", True),
            ("descricao", "Descrição", "texto", True),
            ("categoria", "Categoria", "texto", False),
            ("quantidade", "Quantidade inicial", "decimal", True),
            ("estoque_minimo", "Estoque mínimo", "decimal", True),
            ("custo", "Custo unitário", "decimal", False),
            ("localizacao", "Localização", "texto", False),
            ("status", "Status", ("Ativo", "Inativo"), True),
        ),
    },
    "compras": {
        "nome": "Compras",
        "icone": "⇄",
        "descricao": "Solicitações, fornecedores, valores e aprovações.",
        "cor": "#FB923C",
        "entidade": "solicitacoes_compra",
        "titulo_registro": "Nova solicitação de compra",
        "colunas_tabela": (
            ("item", "Item", 220),
            ("quantidade", "Quantidade", 90),
            ("fornecedor", "Fornecedor", 150),
            ("valor_estimado", "Estimativa", 110),
            ("status", "Status", 100),
        ),
        "campos": (
            ("item", "Item solicitado", "texto", True),
            ("quantidade", "Quantidade", "decimal", True),
            ("fornecedor", "Fornecedor sugerido", "texto", False),
            ("valor_estimado", "Valor estimado", "decimal", False),
            ("centro_custo_id", "Centro de custo", "centro_custo", False),
            ("status", "Status", ("Pendente", "Em cotação", "Aprovado", "Rejeitado"), True),
        ),
    },
    "ti": {
        "nome": "Tecnologia",
        "icone": "⌘",
        "descricao": "Ativos, chamados, prioridades e disponibilidade.",
        "cor": "#06B6D4",
        "entidade": "chamados_ti",
        "titulo_registro": "Novo chamado",
        "colunas_tabela": (
            ("titulo", "Chamado", 230),
            ("categoria", "Categoria", 120),
            ("prioridade", "Prioridade", 100),
            ("responsavel", "Responsável", 140),
            ("status", "Status", 110),
        ),
        "campos": (
            ("titulo", "Título", "texto", True),
            ("categoria", "Categoria", "texto", False),
            ("prioridade", "Prioridade", ("Baixa", "Média", "Alta", "Crítica"), True),
            ("responsavel", "Responsável", "texto", False),
            ("status", "Status", ("Aberto", "Em atendimento", "Aguardando usuário", "Concluído"), True),
        ),
    },
    "marketing": {
        "nome": "Marketing",
        "icone": "◎",
        "descricao": "Campanhas, investimento, leads, conversões e retorno.",
        "cor": "#EC4899",
        "entidade": "campanhas_marketing",
        "titulo_registro": "Nova campanha",
        "colunas_tabela": (
            ("nome", "Campanha", 200),
            ("canal", "Canal", 115),
            ("investimento", "Investimento", 110),
            ("leads", "Leads", 75),
            ("conversoes", "Conversões", 85),
            ("status", "Status", 90),
        ),
        "campos": (
            ("nome", "Nome da campanha", "texto", True),
            ("canal", "Canal", ("Google Ads", "Meta Ads", "LinkedIn", "E-mail", "Orgânico", "Eventos"), True),
            ("investimento", "Investimento", "decimal", False),
            ("leads", "Leads", "inteiro", False),
            ("conversoes", "Conversões", "inteiro", False),
            ("receita", "Receita atribuída", "decimal", False),
            ("status", "Status", ("Planejada", "Ativa", "Pausada", "Concluída"), True),
        ),
    },
    "administrativo": {
        "nome": "Administrativo",
        "icone": "☷",
        "descricao": "Solicitações internas, facilities, viagens e reembolsos.",
        "cor": "#94A3B8",
        "entidade": "solicitacoes_administrativas",
        "titulo_registro": "Nova solicitação interna",
        "colunas_tabela": (
            ("titulo", "Solicitação", 220),
            ("categoria", "Categoria", 125),
            ("solicitante", "Solicitante", 140),
            ("valor", "Valor", 100),
            ("status", "Status", 105),
        ),
        "campos": (
            ("titulo", "Título", "texto", True),
            ("categoria", "Categoria", ("Facilities", "Viagem", "Reembolso", "Manutenção", "Documento", "Outro"), True),
            ("solicitante", "Solicitante", "texto", False),
            ("valor", "Valor estimado", "decimal", False),
            ("centro_custo_id", "Centro de custo", "centro_custo", False),
            ("status", "Status", ("Pendente", "Em análise", "Aprovado", "Rejeitado", "Concluído"), True),
        ),
    },
    "juridico": {
        "nome": "Jurídico",
        "icone": "⚖",
        "descricao": "Contratos, vencimentos, riscos e provisões.",
        "cor": "#EAB308",
        "entidade": "contratos_juridicos",
        "titulo_registro": "Novo contrato",
        "colunas_tabela": (
            ("titulo", "Contrato", 210),
            ("parte", "Parte", 150),
            ("valor", "Valor", 100),
            ("risco", "Risco", 85),
            ("vencimento", "Vencimento", 105),
            ("status", "Status", 90),
        ),
        "campos": (
            ("titulo", "Título do contrato", "texto", True),
            ("parte", "Cliente / parte", "texto", True),
            ("valor", "Valor", "decimal", False),
            ("risco", "Risco", ("Baixo", "Médio", "Alto", "Crítico"), True),
            ("vencimento", "Vencimento", "data", False),
            ("status", "Status", ("Elaboração", "Revisão", "Ativo", "Encerrado"), True),
        ),
    },
    "comercial": {
        "nome": "Comercial",
        "icone": "◇",
        "descricao": "Leads, oportunidades, etapas e previsão de receita.",
        "cor": "#14B8A6",
        "entidade": "oportunidades_comerciais",
        "titulo_registro": "Nova oportunidade",
        "colunas_tabela": (
            ("cliente", "Cliente", 190),
            ("etapa", "Etapa", 125),
            ("valor", "Valor", 110),
            ("responsavel", "Responsável", 140),
            ("status", "Status", 90),
        ),
        "campos": (
            ("cliente", "Cliente / empresa", "texto", True),
            ("etapa", "Etapa", ("Novo", "Qualificado", "Proposta", "Negociação", "Ganho", "Perdido"), True),
            ("valor", "Valor estimado", "decimal", False),
            ("responsavel", "Responsável", "texto", False),
            ("status", "Status", ("Aberto", "Ganho", "Perdido"), True),
        ),
    },
}


ORDEM_MODULOS = tuple(MODULOS)


def obter_modulo(chave: str) -> dict:
    try:
        return MODULOS[chave]
    except KeyError as erro:
        raise ValueError(f"Módulo empresarial desconhecido: {chave}") from erro
