"""Arquitetura visual e funcional dos painéis departamentais da V8."""

from __future__ import annotations


PAINEIS_MODULOS = {
    "rh": {
        "titulo": "Gestão de pessoas",
        "resumo": "Ciclo completo do colaborador, desenvolvimento e operações de RH.",
        "menu": (
            ("visao", "⌂", "Visão geral"),
            ("registros", "◎", "Cadastro operacional"),
            ("colaboradores", "◎", "Colaboradores"),
            ("admissoes", "+", "Admissões"),
            ("desligamentos", "−", "Desligamentos"),
            ("movimentacoes", "⇄", "Movimentações"),
            ("ponto", "◷", "Ponto e jornada"),
            ("ferias", "◷", "Férias e ausências"),
            ("beneficios", "♢", "Benefícios"),
            ("folha", "$", "Folha e custos"),
            ("cargos", "#", "Cargos e salários"),
            ("recrutamento", "◎", "Recrutamento"),
            ("desempenho", "★", "Desempenho"),
            ("treinamentos", "△", "Treinamentos"),
            ("carreira", "↗", "Carreira e PDI"),
            ("documentos", "▤", "Documentos"),
            ("solicitacoes", "✓", "Solicitações"),
            ("relatorios", "▥", "Relatórios"),
        ),
        "acoes": (
            ("Nova admissão", "Inicie o onboarding e distribua tarefas entre RH, TI e Estoque.", "+"),
            ("Planejar férias", "Organize períodos, conflitos e aprovações da equipe.", "◷"),
            ("Fechar folha", "Revise salários, benefícios, variáveis e provisões.", "$"),
        ),
        "acao_destinos": ("admissoes", "ferias", "folha"),
        "fila_titulo": "Jornada do colaborador",
        "etapas": ("Pré-admissão", "Documentação", "Onboarding", "Ativo", "Desligamento"),
        "recursos": ("Portal do colaborador", "Histórico salarial", "Avaliações", "Equipamentos vinculados"),
    },
    "financeiro": {
        "titulo": "Controle financeiro",
        "resumo": "Caixa, obrigações, recebíveis, orçamento e desempenho financeiro.",
        "menu": (
            ("visao", "⌂", "Visão geral"),
            ("registros", "≡", "Lançamentos"),
            ("pagar", "↓", "Contas a pagar"),
            ("receber", "↑", "Contas a receber"),
            ("fluxo", "≋", "Fluxo de caixa"),
            ("bancos", "▣", "Bancos e contas"),
            ("orcamento", "▥", "Orçamento"),
            ("conciliacao", "✓", "Conciliação"),
            ("dre", "▤", "DRE"),
            ("relatorios", "↗", "Relatórios"),
        ),
        "acoes": (
            ("Novo lançamento", "Registre receitas, despesas e seus centros de custo.", "+"),
            ("Conciliação", "Compare movimentações internas e extratos bancários.", "✓"),
            ("Projetar caixa", "Simule saldos e identifique necessidades futuras.", "≋"),
        ),
        "acao_destinos": ("registros", "conciliacao", "fluxo"),
        "fila_titulo": "Ciclo financeiro",
        "etapas": ("Previsto", "A vencer", "Em aprovação", "Liquidado", "Conciliado"),
        "recursos": ("Conciliação bancária", "DRE gerencial", "Forecast", "Recorrências"),
    },
    "estoque": {
        "titulo": "Operações de estoque",
        "resumo": "Produtos, disponibilidade, rastreabilidade e movimentações por local.",
        "menu": (
            ("visao", "⌂", "Visão geral"),
            ("registros", "▣", "Itens e produtos"),
            ("movimentacoes", "⇄", "Movimentações"),
            ("inventario", "✓", "Inventário"),
            ("depositos", "▦", "Depósitos"),
            ("lotes", "#", "Lotes e validade"),
            ("transferencias", "↔", "Transferências"),
            ("alertas", "!", "Alertas"),
            ("relatorios", "▥", "Relatórios"),
        ),
        "acoes": (
            ("Entrada de itens", "Registre recebimentos, lotes e custos de entrada.", "+"),
            ("Saída de itens", "Realize baixas com origem, destino e responsável.", "−"),
            ("Iniciar inventário", "Prepare uma contagem por depósito ou categoria.", "✓"),
        ),
        "acao_destinos": ("movimentacoes", "movimentacoes", "inventario"),
        "fila_titulo": "Fluxo de movimentação",
        "etapas": ("Recebimento", "Conferência", "Armazenagem", "Reserva", "Expedição"),
        "recursos": ("Leitor QR/Barcode", "Lotes e validade", "Inventário cíclico", "Sugestão de reposição"),
    },
    "compras": {
        "titulo": "Compras e suprimentos",
        "resumo": "Solicitações, cotações, fornecedores, pedidos e recebimentos.",
        "menu": (
            ("visao", "⌂", "Visão geral"),
            ("registros", "▤", "Solicitações"),
            ("cotacoes", "≡", "Cotações"),
            ("pedidos", "▣", "Pedidos"),
            ("fornecedores", "◎", "Fornecedores"),
            ("recebimentos", "↓", "Recebimentos"),
            ("contratos", "▧", "Contratos"),
            ("relatorios", "▥", "Relatórios"),
        ),
        "acoes": (
            ("Nova solicitação", "Solicite itens, serviços e aprovação orçamentária.", "+"),
            ("Criar cotação", "Compare preços, prazos e condições de fornecedores.", "≡"),
            ("Registrar recebimento", "Confirme entrega e encaminhe a entrada ao Estoque.", "↓"),
        ),
        "acao_destinos": ("registros", "cotacoes", "recebimentos"),
        "fila_titulo": "Ciclo de suprimentos",
        "etapas": ("Solicitação", "Aprovação", "Cotação", "Pedido", "Recebimento"),
        "recursos": ("Mapa de cotação", "Score de fornecedor", "Pedidos recorrentes", "Integração com Estoque"),
    },
    "ti": {
        "titulo": "Tecnologia e serviços",
        "resumo": "Chamados, ativos, licenças, rede e saúde dos serviços corporativos.",
        "menu": (
            ("visao", "⌂", "Visão geral"),
            ("registros", "◌", "Chamados"),
            ("ativos", "▣", "Ativos"),
            ("rede", "⌘", "Rede"),
            ("licencas", "#", "Licenças"),
            ("sistemas", "▦", "Sistemas"),
            ("monitoramento", "◉", "Monitoramento"),
            ("relatorios", "▥", "Relatórios"),
        ),
        "acoes": (
            ("Abrir chamado", "Registre impacto, prioridade, ativo e responsável.", "+"),
            ("Cadastrar ativo", "Inclua equipamento, patrimônio e responsável atual.", "▣"),
            ("Verificar ambiente", "Visualize disponibilidade e alertas dos serviços.", "◉"),
        ),
        "acao_destinos": ("registros", "ativos", "monitoramento"),
        "fila_titulo": "Atendimento de chamados",
        "etapas": ("Novo", "Triagem", "Em atendimento", "Aguardando", "Resolvido"),
        "recursos": ("Inventário de ativos", "Descoberta autorizada", "Controle de licenças", "SLA e monitoramento"),
    },
    "marketing": {
        "titulo": "Marketing e crescimento",
        "resumo": "Campanhas, canais, leads, calendário e retorno sobre investimento.",
        "menu": (
            ("visao", "⌂", "Visão geral"),
            ("registros", "◎", "Campanhas"),
            ("leads", "◇", "Leads"),
            ("calendario", "◷", "Calendário"),
            ("canais", "≡", "Canais"),
            ("automacao", "↻", "Automações"),
            ("conteudo", "▤", "Conteúdo"),
            ("relatorios", "▥", "Relatórios"),
        ),
        "acoes": (
            ("Nova campanha", "Defina canal, verba, público, período e objetivo.", "+"),
            ("Planejar conteúdo", "Organize pauta, produção, revisão e publicação.", "◷"),
            ("Analisar canais", "Compare leads, conversões, receita e retorno.", "≡"),
        ),
        "acao_destinos": ("registros", "conteudo", "canais"),
        "fila_titulo": "Pipeline de campanha",
        "etapas": ("Planejamento", "Produção", "Revisão", "Ativa", "Concluída"),
        "recursos": ("Calendário editorial", "Automação de campanhas", "Atribuição de receita", "Integração com CRM"),
    },
    "administrativo": {
        "titulo": "Operações administrativas",
        "resumo": "Solicitações internas, facilities, viagens, reembolsos e recursos.",
        "menu": (
            ("visao", "⌂", "Visão geral"),
            ("registros", "▤", "Solicitações"),
            ("facilities", "⌂", "Facilities"),
            ("viagens", "↗", "Viagens"),
            ("reembolsos", "$", "Reembolsos"),
            ("veiculos", "▣", "Veículos"),
            ("salas", "▦", "Salas e reservas"),
            ("documentos", "▤", "Documentos"),
            ("relatorios", "▥", "Relatórios"),
        ),
        "acoes": (
            ("Nova solicitação", "Registre uma demanda interna e sua classificação.", "+"),
            ("Reservar recurso", "Planeje salas, veículos e recursos compartilhados.", "▦"),
            ("Solicitar reembolso", "Envie despesas para conferência e aprovação.", "$"),
        ),
        "acao_destinos": ("registros", "salas", "reembolsos"),
        "fila_titulo": "Atendimento interno",
        "etapas": ("Solicitado", "Triagem", "Em aprovação", "Em execução", "Concluído"),
        "recursos": ("Reservas corporativas", "Gestão de viagens", "Facilities", "Reembolsos integrados"),
    },
    "juridico": {
        "titulo": "Operações jurídicas",
        "resumo": "Contratos, processos, prazos, riscos e provisões com rastreabilidade.",
        "menu": (
            ("visao", "⌂", "Visão geral"),
            ("registros", "▧", "Contratos"),
            ("processos", "⚖", "Processos"),
            ("prazos", "◷", "Prazos"),
            ("audiencias", "◎", "Audiências"),
            ("riscos", "!", "Riscos e provisões"),
            ("documentos", "▤", "Documentos"),
            ("relatorios", "▥", "Relatórios"),
        ),
        "acoes": (
            ("Novo contrato", "Inicie elaboração, revisão e fluxo de aprovação.", "+"),
            ("Cadastrar processo", "Organize partes, risco, valor, responsável e movimentações.", "⚖"),
            ("Registrar prazo", "Associe obrigação, vencimento e responsável.", "◷"),
        ),
        "acao_destinos": ("registros", "processos", "prazos"),
        "fila_titulo": "Ciclo jurídico",
        "etapas": ("Entrada", "Análise", "Revisão", "Aprovação", "Vigência"),
        "recursos": ("Gestão de processos", "Agenda de prazos", "Matriz de risco", "Provisões financeiras"),
    },
    "comercial": {
        "titulo": "Operações comerciais",
        "resumo": "CRM, leads, oportunidades, propostas, metas e previsão de receita.",
        "menu": (
            ("visao", "⌂", "Visão geral"),
            ("registros", "◇", "Oportunidades"),
            ("crm", "◎", "CRM"),
            ("leads", "+", "Leads"),
            ("pipeline", "⇄", "Pipeline"),
            ("propostas", "▤", "Propostas"),
            ("clientes", "◎", "Clientes"),
            ("metas", "◉", "Metas"),
            ("relatorios", "▥", "Relatórios"),
        ),
        "acoes": (
            ("Novo lead", "Registre origem, interesse, responsável e próxima ação.", "+"),
            ("Nova oportunidade", "Defina etapa, valor, probabilidade e previsão de fechamento.", "◇"),
            ("Criar proposta", "Prepare uma proposta ligada ao cliente e à oportunidade.", "▤"),
        ),
        "acao_destinos": ("leads", "registros", "propostas"),
        "fila_titulo": "Pipeline comercial",
        "etapas": ("Novo lead", "Qualificado", "Proposta", "Negociação", "Fechamento"),
        "recursos": ("CRM compartilhado", "Funil visual", "Metas por equipe", "Forecast comercial"),
    },
}


# Campos complementares persistidos em ``dados_json``. Os nomes são
# deliberadamente semânticos: uma admissão não pode parecer um contrato, nem
# uma licença de software pode abrir o formulário genérico de "identificação".
ESQUEMAS_RECURSOS = {
    "colaboradores": (("nome", "Nome completo", "texto"), ("matricula", "Matrícula", "texto"), ("cargo", "Cargo", "texto"), ("departamento", "Departamento", "texto"), ("admissao", "Admissão", "data"), ("status", "Situação", "opcoes", ("Pré-admissão", "Ativo", "Em desligamento", "Desligado"))),
    "ponto": (("colaborador", "Colaborador", "texto"), ("data", "Data", "data"), ("entrada", "Entrada", "texto"), ("saida", "Saída", "texto"), ("justificativa", "Justificativa", "texto"), ("status", "Situação", "opcoes", ("Registrado", "Ajustado", "Aprovado"))),
    "cargos": (("codigo", "Código", "texto"), ("titulo", "Título", "texto"), ("nivel", "Nível", "texto"), ("faixa_minima", "Faixa mínima", "moeda"), ("faixa_maxima", "Faixa máxima", "moeda"), ("status", "Situação", "opcoes", ("Ativo", "Inativo"))),
    "recrutamento": (("vaga", "Vaga", "texto"), ("departamento", "Departamento", "texto"), ("quantidade", "Quantidade", "numero"), ("responsavel", "Responsável", "texto"), ("motivo", "Motivo", "texto"), ("status", "Situação", "opcoes", ("Rascunho", "Aguardando aprovação", "Aberta", "Encerrada"))),
    "desempenho": (("colaborador", "Colaborador", "texto"), ("ciclo", "Ciclo", "texto"), ("tipo_avaliacao", "Tipo", "texto"), ("nota", "Nota", "numero"), ("avaliador", "Avaliador", "texto"), ("status", "Situação", "opcoes", ("Planejada", "Em andamento", "Concluída"))),
    "treinamentos": (("titulo", "Treinamento", "texto"), ("tipo_treinamento", "Tipo", "texto"), ("carga_horaria", "Carga horária", "numero"), ("validade", "Validade", "texto"), ("custo", "Custo", "moeda"), ("status", "Situação", "opcoes", ("Ativo", "Concluído", "Cancelado"))),
    "carreira": (("colaborador", "Colaborador", "texto"), ("titulo", "Plano de desenvolvimento", "texto"), ("objetivo", "Objetivo", "texto"), ("inicio", "Início", "data"), ("prazo", "Prazo", "data"), ("status", "Situação", "opcoes", ("Ativo", "Concluído", "Cancelado"))),
    "solicitacoes": (("colaborador", "Colaborador", "texto"), ("tipo_solicitacao", "Tipo", "texto"), ("titulo", "Título", "texto"), ("descricao", "Descrição", "texto"), ("responsavel", "Responsável", "texto"), ("status", "Situação", "opcoes", ("Aberta", "Em análise", "Aprovada", "Rejeitada", "Concluída"))),
    "admissoes": (("colaborador", "Colaborador", "texto"), ("cargo", "Cargo", "texto"), ("departamento", "Departamento", "texto"), ("data_admissao", "Data de admissão", "data"), ("gestor", "Gestor", "texto"), ("status", "Etapa", "opcoes", ("Pré-admissão", "Documentação", "Onboarding", "Concluído"))),
    "desligamentos": (("colaborador", "Colaborador", "texto"), ("motivo", "Motivo", "texto"), ("data_desligamento", "Data do desligamento", "data"), ("responsavel", "Responsável", "texto"), ("status", "Etapa", "opcoes", ("Solicitado", "Em processamento", "Concluído", "Cancelado"))),
    "ferias": (("colaborador", "Colaborador", "texto"), ("inicio", "Início", "data"), ("fim", "Término", "data"), ("dias", "Quantidade de dias", "numero"), ("status", "Situação", "opcoes", ("Planejado", "Pendente", "Aprovado", "Concluído"))),
    "beneficios": (("colaborador", "Colaborador", "texto"), ("tipo_beneficio", "Tipo de benefício", "texto"), ("operadora", "Operadora", "texto"), ("custo", "Custo mensal", "moeda"), ("vigencia", "Início da vigência", "data"), ("status", "Situação", "opcoes", ("Ativo", "Suspenso", "Encerrado"))),
    "folha": (("competencia", "Competência", "texto"), ("colaborador", "Colaborador / grupo", "texto"), ("valor_bruto", "Valor bruto", "moeda"), ("descontos", "Descontos", "moeda"), ("valor_liquido", "Valor líquido", "moeda"), ("status", "Situação", "opcoes", ("Rascunho", "Em conferência", "Fechado", "Pago"))),
    "documentos": (("titulo", "Título", "texto"), ("tipo_documento", "Tipo de documento", "texto"), ("vinculo", "Pessoa / processo relacionado", "texto"), ("validade", "Validade", "data"), ("responsavel", "Responsável", "texto"), ("status", "Situação", "opcoes", ("Ativo", "Vencendo", "Vencido", "Arquivado"))),
    "relatorios": (("titulo", "Título do relatório", "texto"), ("periodo", "Período", "texto"), ("formato", "Formato", "opcoes", ("PDF", "Excel", "CSV", "HTML")), ("responsavel", "Responsável", "texto"), ("status", "Situação", "opcoes", ("Rascunho", "Gerando", "Concluído", "Falhou"))),
    "pagar": (("fornecedor", "Fornecedor", "texto"), ("descricao", "Descrição", "texto"), ("vencimento", "Vencimento", "data"), ("valor", "Valor", "moeda"), ("status", "Situação", "opcoes", ("Pendente", "Agendado", "Pago", "Vencido"))),
    "receber": (("cliente", "Cliente", "texto"), ("descricao", "Descrição", "texto"), ("vencimento", "Vencimento", "data"), ("valor", "Valor", "moeda"), ("status", "Situação", "opcoes", ("Pendente", "Recebido", "Vencido", "Renegociado"))),
    "fluxo": (("periodo", "Período", "texto"), ("saldo_inicial", "Saldo inicial", "moeda"), ("entradas", "Entradas", "moeda"), ("saidas", "Saídas", "moeda"), ("saldo_final", "Saldo projetado", "moeda"), ("status", "Cenário", "opcoes", ("Realizado", "Projetado", "Simulado"))),
    "bancos": (("banco", "Banco", "texto"), ("agencia", "Agência", "texto"), ("conta", "Conta", "texto"), ("tipo_conta", "Tipo", "opcoes", ("Corrente", "Poupança", "Investimento")), ("saldo", "Saldo", "moeda"), ("status", "Situação", "opcoes", ("Ativa", "Bloqueada", "Encerrada"))),
    "orcamento": (("centro_custo", "Centro de custo", "texto"), ("periodo", "Período", "texto"), ("previsto", "Previsto", "moeda"), ("realizado", "Realizado", "moeda"), ("responsavel", "Responsável", "texto"), ("status", "Situação", "opcoes", ("Planejado", "Aprovado", "Revisão", "Encerrado"))),
    "conciliacao": (("conta", "Conta bancária", "texto"), ("data_movimento", "Data", "data"), ("descricao", "Movimentação", "texto"), ("valor", "Valor", "moeda"), ("referencia", "Referência interna", "texto"), ("status", "Conciliação", "opcoes", ("Pendente", "Conciliado", "Divergente"))),
    "dre": (("competencia", "Competência", "texto"), ("receita", "Receita", "moeda"), ("custos", "Custos", "moeda"), ("despesas", "Despesas", "moeda"), ("resultado", "Resultado", "moeda"), ("status", "Situação", "opcoes", ("Prévia", "Fechada"))),
    "movimentacoes": (("item", "Item / SKU", "texto"), ("tipo_movimento", "Movimento", "opcoes", ("Entrada", "Saída", "Ajuste", "Transferência")), ("quantidade", "Quantidade", "numero"), ("origem_destino", "Origem / destino", "texto"), ("responsavel", "Responsável", "texto"), ("status", "Situação", "opcoes", ("Pendente", "Confirmado", "Cancelado"))),
    "inventario": (("nome", "Inventário", "texto"), ("deposito", "Depósito", "texto"), ("inicio", "Data de início", "data"), ("responsavel", "Responsável", "texto"), ("divergencias", "Divergências", "numero"), ("status", "Situação", "opcoes", ("Planejado", "Em contagem", "Em conferência", "Concluído"))),
    "depositos": (("nome", "Depósito", "texto"), ("codigo", "Código", "texto"), ("localizacao", "Localização", "texto"), ("responsavel", "Responsável", "texto"), ("capacidade", "Capacidade", "numero"), ("status", "Situação", "opcoes", ("Ativo", "Inativo", "Manutenção"))),
    "lotes": (("item", "Item", "texto"), ("lote", "Lote", "texto"), ("quantidade", "Quantidade", "numero"), ("fabricacao", "Fabricação", "data"), ("validade", "Validade", "data"), ("status", "Situação", "opcoes", ("Disponível", "Bloqueado", "Vencendo", "Vencido"))),
    "transferencias": (("item", "Item", "texto"), ("quantidade", "Quantidade", "numero"), ("origem", "Depósito de origem", "texto"), ("destino", "Depósito de destino", "texto"), ("responsavel", "Responsável", "texto"), ("status", "Situação", "opcoes", ("Solicitada", "Em trânsito", "Recebida", "Cancelada"))),
    "alertas": (("item", "Item / indicador", "texto"), ("tipo_alerta", "Tipo de alerta", "texto"), ("limite", "Limite", "numero"), ("valor_atual", "Valor atual", "numero"), ("responsavel", "Responsável", "texto"), ("status", "Situação", "opcoes", ("Aberto", "Reconhecido", "Resolvido"))),
    "cotacoes": (("solicitacao", "Solicitação", "texto"), ("fornecedor", "Fornecedor", "texto"), ("valor", "Valor cotado", "moeda"), ("prazo_dias", "Prazo em dias", "numero"), ("validade", "Validade da proposta", "data"), ("status", "Situação", "opcoes", ("Recebida", "Em análise", "Selecionada", "Descartada"))),
    "pedidos": (("numero", "Número do pedido", "texto"), ("fornecedor", "Fornecedor", "texto"), ("valor", "Valor", "moeda"), ("emissao", "Emissão", "data"), ("previsao", "Previsão de entrega", "data"), ("status", "Situação", "opcoes", ("Emitido", "Confirmado", "Parcial", "Recebido", "Cancelado"))),
    "fornecedores": (("razao_social", "Razão social", "texto"), ("cnpj", "CNPJ", "texto"), ("categoria", "Categoria", "texto"), ("contato", "Contato", "texto"), ("avaliacao", "Avaliação", "numero"), ("status", "Situação", "opcoes", ("Ativo", "Em homologação", "Bloqueado"))),
    "recebimentos": (("pedido", "Pedido", "texto"), ("fornecedor", "Fornecedor", "texto"), ("data_recebimento", "Data de recebimento", "data"), ("documento", "Nota / documento", "texto"), ("divergencias", "Divergências", "texto"), ("status", "Situação", "opcoes", ("Pendente", "Conferido", "Recebido com divergência"))),
    "contratos": (("titulo", "Contrato", "texto"), ("parte", "Parte / fornecedor", "texto"), ("inicio", "Início", "data"), ("fim", "Término", "data"), ("valor", "Valor", "moeda"), ("status", "Situação", "opcoes", ("Rascunho", "Em revisão", "Ativo", "Encerrado"))),
    "ativos": (("patrimonio", "Patrimônio", "texto"), ("equipamento", "Equipamento", "texto"), ("tipo_ativo", "Tipo", "texto"), ("responsavel", "Responsável", "texto"), ("endereco_ip", "Endereço IP", "texto"), ("status", "Situação", "opcoes", ("Disponível", "Em uso", "Manutenção", "Baixado"))),
    "rede": (("dispositivo", "Dispositivo", "texto"), ("endereco_ip", "Endereço IP", "texto"), ("mac", "MAC", "texto"), ("localizacao", "Localização", "texto"), ("ultima_verificacao", "Última verificação", "data"), ("status", "Situação", "opcoes", ("Online", "Offline", "Desconhecido"))),
    "licencas": (("software", "Software", "texto"), ("fornecedor", "Fornecedor", "texto"), ("total", "Licenças contratadas", "numero"), ("utilizadas", "Licenças utilizadas", "numero"), ("vencimento", "Vencimento", "data"), ("status", "Situação", "opcoes", ("Ativa", "Vencendo", "Expirada"))),
    "sistemas": (("sistema", "Sistema", "texto"), ("proprietario", "Proprietário", "texto"), ("criticidade", "Criticidade", "opcoes", ("Baixa", "Média", "Alta", "Crítica")), ("url", "URL / endpoint", "texto"), ("disponibilidade", "Disponibilidade %", "numero"), ("status", "Situação", "opcoes", ("Operacional", "Degradado", "Indisponível"))),
    "monitoramento": (("servico", "Serviço", "texto"), ("metrica", "Métrica", "texto"), ("valor_atual", "Valor atual", "numero"), ("limite", "Limite", "numero"), ("ultima_coleta", "Última coleta", "data"), ("status", "Situação", "opcoes", ("Normal", "Atenção", "Crítico"))),
    "leads": (("nome", "Lead", "texto"), ("empresa", "Empresa", "texto"), ("origem", "Origem", "texto"), ("responsavel", "Responsável", "texto"), ("proxima_acao", "Próxima ação", "data"), ("status", "Situação", "opcoes", ("Novo", "Qualificado", "Descartado", "Convertido"))),
    "calendario": (("titulo", "Conteúdo / campanha", "texto"), ("canal", "Canal", "texto"), ("data_publicacao", "Publicação", "data"), ("responsavel", "Responsável", "texto"), ("formato", "Formato", "texto"), ("status", "Situação", "opcoes", ("Ideia", "Produção", "Revisão", "Aprovado", "Publicado"))),
    "canais": (("canal", "Canal", "texto"), ("investimento", "Investimento", "moeda"), ("leads", "Leads", "numero"), ("conversoes", "Conversões", "numero"), ("receita", "Receita atribuída", "moeda"), ("status", "Situação", "opcoes", ("Ativo", "Pausado", "Encerrado"))),
    "automacao": (("nome", "Automação", "texto"), ("gatilho", "Gatilho", "texto"), ("acao", "Ação", "texto"), ("publico", "Público", "texto"), ("ultima_execucao", "Última execução", "data"), ("status", "Situação", "opcoes", ("Ativa", "Pausada", "Falhou"))),
    "conteudo": (("titulo", "Título", "texto"), ("canal", "Canal", "texto"), ("formato", "Formato", "texto"), ("responsavel", "Responsável", "texto"), ("publicacao", "Publicação", "data"), ("status", "Etapa", "opcoes", ("Ideia", "Produção", "Revisão", "Aprovado", "Publicado"))),
    "facilities": (("demanda", "Demanda", "texto"), ("local", "Local", "texto"), ("categoria", "Categoria", "texto"), ("responsavel", "Responsável", "texto"), ("prazo", "Prazo", "data"), ("status", "Situação", "opcoes", ("Aberto", "Em atendimento", "Concluído"))),
    "viagens": (("viajante", "Viajante", "texto"), ("destino", "Destino", "texto"), ("ida", "Data de ida", "data"), ("volta", "Data de volta", "data"), ("custo", "Custo previsto", "moeda"), ("status", "Situação", "opcoes", ("Solicitada", "Aprovada", "Realizada", "Cancelada"))),
    "reembolsos": (("solicitante", "Solicitante", "texto"), ("categoria", "Categoria", "texto"), ("data_despesa", "Data da despesa", "data"), ("valor", "Valor", "moeda"), ("comprovante", "Comprovante", "texto"), ("status", "Situação", "opcoes", ("Pendente", "Em conferência", "Aprovado", "Pago", "Rejeitado"))),
    "veiculos": (("veiculo", "Veículo", "texto"), ("placa", "Placa", "texto"), ("responsavel", "Responsável", "texto"), ("quilometragem", "Quilometragem", "numero"), ("proxima_revisao", "Próxima revisão", "data"), ("status", "Situação", "opcoes", ("Disponível", "Em uso", "Manutenção"))),
    "salas": (("sala", "Sala / recurso", "texto"), ("solicitante", "Solicitante", "texto"), ("data", "Data", "data"), ("horario", "Horário", "texto"), ("finalidade", "Finalidade", "texto"), ("status", "Situação", "opcoes", ("Reservada", "Confirmada", "Cancelada"))),
    "processos": (("numero", "Número do processo", "texto"), ("parte", "Parte", "texto"), ("tribunal", "Tribunal", "texto"), ("advogado", "Advogado responsável", "texto"), ("valor", "Valor em risco", "moeda"), ("status", "Situação", "opcoes", ("Ativo", "Suspenso", "Encerrado"))),
    "prazos": (("obrigacao", "Obrigação", "texto"), ("processo", "Processo / contrato", "texto"), ("vencimento", "Vencimento", "data"), ("responsavel", "Responsável", "texto"), ("criticidade", "Criticidade", "opcoes", ("Baixa", "Média", "Alta", "Crítica")), ("status", "Situação", "opcoes", ("Pendente", "Cumprido", "Vencido"))),
    "audiencias": (("processo", "Processo", "texto"), ("data", "Data", "data"), ("horario", "Horário", "texto"), ("local", "Local / link", "texto"), ("advogado", "Advogado", "texto"), ("status", "Situação", "opcoes", ("Agendada", "Realizada", "Redesignada", "Cancelada"))),
    "riscos": (("referencia", "Processo / contrato", "texto"), ("categoria", "Categoria de risco", "texto"), ("probabilidade", "Probabilidade %", "numero"), ("impacto", "Impacto estimado", "moeda"), ("provisao", "Provisão recomendada", "moeda"), ("status", "Situação", "opcoes", ("Monitorado", "Mitigando", "Materializado", "Encerrado"))),
    "crm": (("contato", "Contato / empresa", "texto"), ("origem", "Origem", "texto"), ("responsavel", "Responsável", "texto"), ("ultima_interacao", "Última interação", "data"), ("proxima_acao", "Próxima ação", "data"), ("status", "Relacionamento", "opcoes", ("Prospect", "Ativo", "Inativo"))),
    "pipeline": (("oportunidade", "Oportunidade", "texto"), ("cliente", "Cliente", "texto"), ("etapa", "Etapa", "opcoes", ("Qualificação", "Proposta", "Negociação", "Fechamento")), ("valor", "Valor", "moeda"), ("probabilidade", "Probabilidade %", "numero"), ("status", "Situação", "opcoes", ("Aberta", "Ganha", "Perdida"))),
    "propostas": (("numero", "Número da proposta", "texto"), ("cliente", "Cliente", "texto"), ("oportunidade", "Oportunidade", "texto"), ("valor", "Valor", "moeda"), ("validade", "Validade", "data"), ("status", "Situação", "opcoes", ("Rascunho", "Enviada", "Aceita", "Recusada"))),
    "clientes": (("nome", "Cliente", "texto"), ("documento", "CPF / CNPJ", "texto"), ("segmento", "Segmento", "texto"), ("contato", "Contato", "texto"), ("responsavel", "Responsável", "texto"), ("status", "Situação", "opcoes", ("Ativo", "Inativo", "Prospect"))),
    "metas": (("nome", "Meta", "texto"), ("responsavel", "Responsável / equipe", "texto"), ("periodo", "Período", "texto"), ("valor_meta", "Valor da meta", "moeda"), ("realizado", "Realizado", "moeda"), ("status", "Situação", "opcoes", ("Em andamento", "Atingida", "Não atingida"))),
}


def obter_esquema_recurso(secao):
    return ESQUEMAS_RECURSOS.get(
        secao,
        (("nome", "Nome", "texto"), ("descricao", "Descrição", "texto"), ("responsavel", "Responsável", "texto"), ("status", "Situação", "opcoes", ("Pendente", "Em andamento", "Concluído"))),
    )
