"""Arquitetura visual dos painéis departamentais da V7.

Os itens marcados como ``preview`` possuem apenas interface nesta etapa. O
catálogo deixa explícito o escopo futuro sem acoplar regras de negócio à UI.
"""

from __future__ import annotations


PAINEIS_MODULOS = {
    "rh": {
        "titulo": "Gestão de pessoas",
        "resumo": "Ciclo completo do colaborador, desenvolvimento e operações de RH.",
        "menu": (
            ("visao", "⌂", "Visão geral"),
            ("registros", "◎", "Colaboradores"),
            ("admissoes", "+", "Admissões"),
            ("desligamentos", "−", "Desligamentos"),
            ("ferias", "◷", "Férias e ausências"),
            ("beneficios", "♢", "Benefícios"),
            ("folha", "$", "Folha e custos"),
            ("documentos", "▤", "Documentos"),
            ("relatorios", "▥", "Relatórios"),
        ),
        "acoes": (
            ("Nova admissão", "Inicie o onboarding e distribua tarefas entre RH, TI e Estoque.", "+"),
            ("Planejar férias", "Organize períodos, conflitos e aprovações da equipe.", "◷"),
            ("Fechar folha", "Revise salários, benefícios, variáveis e provisões.", "$"),
        ),
        "fila_titulo": "Jornada do colaborador",
        "etapas": ("Pré-admissão", "Documentação", "Onboarding", "Ativo", "Desligamento"),
        "recursos": ("Portal do colaborador", "Histórico salarial", "Avaliações", "Equipamentos vinculados"),
    },
    "financeiro": {
        "titulo": "Controle financeiro",
        "resumo": "Caixa, obrigações, recebíveis, orçamento e desempenho financeiro.",
        "menu": (
            ("visao", "⌂", "Visão geral"),
            ("registros", "≡", "Lançamentos"),
            ("pagar", "↓", "Contas a pagar"),
            ("receber", "↑", "Contas a receber"),
            ("fluxo", "≋", "Fluxo de caixa"),
            ("bancos", "▣", "Bancos e contas"),
            ("orcamento", "▥", "Orçamento"),
            ("conciliacao", "✓", "Conciliação"),
            ("dre", "▤", "DRE"),
            ("relatorios", "↗", "Relatórios"),
        ),
        "acoes": (
            ("Novo lançamento", "Registre receitas, despesas e seus centros de custo.", "+"),
            ("Conciliação", "Compare movimentações internas e extratos bancários.", "✓"),
            ("Projetar caixa", "Simule saldos e identifique necessidades futuras.", "≋"),
        ),
        "fila_titulo": "Ciclo financeiro",
        "etapas": ("Previsto", "A vencer", "Em aprovação", "Liquidado", "Conciliado"),
        "recursos": ("Conciliação bancária", "DRE gerencial", "Forecast", "Recorrências"),
    },
    "estoque": {
        "titulo": "Operações de estoque",
        "resumo": "Produtos, disponibilidade, rastreabilidade e movimentações por local.",
        "menu": (
            ("visao", "⌂", "Visão geral"),
            ("registros", "▣", "Itens e produtos"),
            ("movimentacoes", "⇄", "Movimentações"),
            ("inventario", "✓", "Inventário"),
            ("depositos", "▦", "Depósitos"),
            ("lotes", "#", "Lotes e validade"),
            ("transferencias", "↔", "Transferências"),
            ("alertas", "!", "Alertas"),
            ("relatorios", "▥", "Relatórios"),
        ),
        "acoes": (
            ("Entrada de itens", "Registre recebimentos, lotes e custos de entrada.", "+"),
            ("Saída de itens", "Realize baixas com origem, destino e responsável.", "−"),
            ("Iniciar inventário", "Prepare uma contagem por depósito ou categoria.", "✓"),
        ),
        "fila_titulo": "Fluxo de movimentação",
        "etapas": ("Recebimento", "Conferência", "Armazenagem", "Reserva", "Expedição"),
        "recursos": ("Leitor QR/Barcode", "Lotes e validade", "Inventário cíclico", "Sugestão de reposição"),
    },
    "compras": {
        "titulo": "Compras e suprimentos",
        "resumo": "Solicitações, cotações, fornecedores, pedidos e recebimentos.",
        "menu": (
            ("visao", "⌂", "Visão geral"),
            ("registros", "▤", "Solicitações"),
            ("cotacoes", "≡", "Cotações"),
            ("pedidos", "▣", "Pedidos"),
            ("fornecedores", "◎", "Fornecedores"),
            ("recebimentos", "↓", "Recebimentos"),
            ("contratos", "▧", "Contratos"),
            ("relatorios", "▥", "Relatórios"),
        ),
        "acoes": (
            ("Nova solicitação", "Solicite itens, serviços e aprovação orçamentária.", "+"),
            ("Criar cotação", "Compare preços, prazos e condições de fornecedores.", "≡"),
            ("Registrar recebimento", "Confirme entrega e encaminhe a entrada ao Estoque.", "↓"),
        ),
        "fila_titulo": "Ciclo de suprimentos",
        "etapas": ("Solicitação", "Aprovação", "Cotação", "Pedido", "Recebimento"),
        "recursos": ("Mapa de cotação", "Score de fornecedor", "Pedidos recorrentes", "Integração com Estoque"),
    },
    "ti": {
        "titulo": "Tecnologia e serviços",
        "resumo": "Chamados, ativos, licenças, rede e saúde dos serviços corporativos.",
        "menu": (
            ("visao", "⌂", "Visão geral"),
            ("registros", "◌", "Chamados"),
            ("ativos", "▣", "Ativos"),
            ("rede", "⌘", "Rede"),
            ("licencas", "#", "Licenças"),
            ("sistemas", "▦", "Sistemas"),
            ("monitoramento", "◉", "Monitoramento"),
            ("relatorios", "▥", "Relatórios"),
        ),
        "acoes": (
            ("Abrir chamado", "Registre impacto, prioridade, ativo e responsável.", "+"),
            ("Cadastrar ativo", "Inclua equipamento, patrimônio e responsável atual.", "▣"),
            ("Verificar ambiente", "Visualize disponibilidade e alertas dos serviços.", "◉"),
        ),
        "fila_titulo": "Atendimento de chamados",
        "etapas": ("Novo", "Triagem", "Em atendimento", "Aguardando", "Resolvido"),
        "recursos": ("Inventário de ativos", "Descoberta autorizada", "Controle de licenças", "SLA e monitoramento"),
    },
    "marketing": {
        "titulo": "Marketing e crescimento",
        "resumo": "Campanhas, canais, leads, calendário e retorno sobre investimento.",
        "menu": (
            ("visao", "⌂", "Visão geral"),
            ("registros", "◎", "Campanhas"),
            ("leads", "◇", "Leads"),
            ("calendario", "◷", "Calendário"),
            ("canais", "≡", "Canais"),
            ("automacao", "↻", "Automações"),
            ("conteudo", "▤", "Conteúdo"),
            ("relatorios", "▥", "Relatórios"),
        ),
        "acoes": (
            ("Nova campanha", "Defina canal, verba, público, período e objetivo.", "+"),
            ("Planejar conteúdo", "Organize pauta, produção, revisão e publicação.", "◷"),
            ("Analisar canais", "Compare leads, conversões, receita e retorno.", "≡"),
        ),
        "fila_titulo": "Pipeline de campanha",
        "etapas": ("Planejamento", "Produção", "Revisão", "Ativa", "Concluída"),
        "recursos": ("Calendário editorial", "Automação de campanhas", "Atribuição de receita", "Integração com CRM"),
    },
    "administrativo": {
        "titulo": "Operações administrativas",
        "resumo": "Solicitações internas, facilities, viagens, reembolsos e recursos.",
        "menu": (
            ("visao", "⌂", "Visão geral"),
            ("registros", "▤", "Solicitações"),
            ("facilities", "⌂", "Facilities"),
            ("viagens", "↗", "Viagens"),
            ("reembolsos", "$", "Reembolsos"),
            ("veiculos", "▣", "Veículos"),
            ("salas", "▦", "Salas e reservas"),
            ("documentos", "▤", "Documentos"),
            ("relatorios", "▥", "Relatórios"),
        ),
        "acoes": (
            ("Nova solicitação", "Registre uma demanda interna e sua classificação.", "+"),
            ("Reservar recurso", "Planeje salas, veículos e recursos compartilhados.", "▦"),
            ("Solicitar reembolso", "Envie despesas para conferência e aprovação.", "$"),
        ),
        "fila_titulo": "Atendimento interno",
        "etapas": ("Solicitado", "Triagem", "Em aprovação", "Em execução", "Concluído"),
        "recursos": ("Reservas corporativas", "Gestão de viagens", "Facilities", "Reembolsos integrados"),
    },
    "juridico": {
        "titulo": "Operações jurídicas",
        "resumo": "Contratos, processos, prazos, riscos e provisões com rastreabilidade.",
        "menu": (
            ("visao", "⌂", "Visão geral"),
            ("registros", "▧", "Contratos"),
            ("processos", "⚖", "Processos"),
            ("prazos", "◷", "Prazos"),
            ("audiencias", "◎", "Audiências"),
            ("riscos", "!", "Riscos e provisões"),
            ("documentos", "▤", "Documentos"),
            ("relatorios", "▥", "Relatórios"),
        ),
        "acoes": (
            ("Novo contrato", "Inicie elaboração, revisão e fluxo de aprovação.", "+"),
            ("Cadastrar processo", "Organize partes, risco, valor, responsável e movimentações.", "⚖"),
            ("Registrar prazo", "Associe obrigação, vencimento e responsável.", "◷"),
        ),
        "fila_titulo": "Ciclo jurídico",
        "etapas": ("Entrada", "Análise", "Revisão", "Aprovação", "Vigência"),
        "recursos": ("Gestão de processos", "Agenda de prazos", "Matriz de risco", "Provisões financeiras"),
    },
    "comercial": {
        "titulo": "Operações comerciais",
        "resumo": "CRM, leads, oportunidades, propostas, metas e previsão de receita.",
        "menu": (
            ("visao", "⌂", "Visão geral"),
            ("registros", "◇", "Oportunidades"),
            ("crm", "◎", "CRM"),
            ("leads", "+", "Leads"),
            ("pipeline", "⇄", "Pipeline"),
            ("propostas", "▤", "Propostas"),
            ("clientes", "◎", "Clientes"),
            ("metas", "◉", "Metas"),
            ("relatorios", "▥", "Relatórios"),
        ),
        "acoes": (
            ("Novo lead", "Registre origem, interesse, responsável e próxima ação.", "+"),
            ("Nova oportunidade", "Defina etapa, valor, probabilidade e previsão de fechamento.", "◇"),
            ("Criar proposta", "Prepare uma proposta ligada ao cliente e à oportunidade.", "▤"),
        ),
        "fila_titulo": "Pipeline comercial",
        "etapas": ("Novo lead", "Qualificado", "Proposta", "Negociação", "Fechamento"),
        "recursos": ("CRM compartilhado", "Funil visual", "Metas por equipe", "Forecast comercial"),
    },
}

